### ISSUE TITLE
Error: skip not supported yet

### ISSUE THREAD

**Issue by jonbaer** [mapd/mapd-connector#36]
Can anyone decipher this error message ... node version v6.11.3

All tables available at metis.mapd.com: [ 'flights_donotmodify',
  'contributions_donotmodify',
  'tweets_nov_feb',
  'zipcodes' ]
Error: skip not supported yet
    at TJSONProtocol.module.exports.TJSONProtocol.skip (/mapd/mapd-connector/dist/node-connector.js:7072:10)
    at Object.module.exports.TColumnType.read (/mapd/mapd-connector/dist/node-connector.js:11021:16)
    at Object.module.exports.TTableDetails.read (/mapd/mapd-connector/dist/node-connector.js:13511:22)
    at Object.module.exports.MapD_get_table_details_result.read (/mapd/mapd-connector/dist/node-connector.js:15265:25)
    at Object.module.exports.MapDClient.recv_get_table_details (/mapd/mapd-connector/dist/node-connector.js:21543:11)
    at decodeCallback (/mapd/mapd-connector/dist/node-connector.js:1998:42)
    at /mapd/mapd-connector/dist/node-connector.js:799:6
    at IncomingMessage.<anonymous> (/mapd/mapd-connector/dist/node-connector.js:2050:47)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

For reference: https://github.com/apache/thrift/blob/master/lib/nodejs/lib/thrift/json_protocol.js#L741

**Comment by mikemoser** [comment]
+1

**Comment by mrblueblue** [comment]
I believe this issue is due to `master` having outdated `thrift` files.

Having updated the files on another branch off `master`, I see that the issue goes away.

Fix coming to `master` soon.

**Comment by jonbaer** [comment]
Just confirming that this is now OK on master branch.
