### ISSUE TITLE
Error not handled when client tries to connect and MapD server is down.

### ISSUE THREAD

**Issue by pratik-dimebox** [mapd/mapd-connector#90]
🐞  
 - MacOS Sierra 10.12.6
 - Steps to recreate: 
        1. Turn down the MapD Server
        2. Try to connect to the server with the connect() function
 - Description of issue:
        When the MapD server is down and we try to connect to the server then the error is not 
        propagated forward to the callback. There is an error thrown to the console which is something 
        like this:
                       <addr>
                       { Error: getaddrinfo ENOTFOUND mapd mapd:9090
                        at errnoException (dns.js:50:10)
                        at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
                        code: 'ENOTFOUND',
                        errno: 'ENOTFOUND',
                        syscall: 'getaddrinfo',
                        hostname: 'mapd',
                        host: 'mapd',
                        port: '9090' }
                        <addr>
        This error should be sent to the callback of the function connect(). But it is not sent and the 
        process stops.
        A similar kind of issue occurs in the functions getFIelds() or query(). To recreate it you have to turn  
        up the MapD server and establish a connection and keep this connection cached. Now turn down   
        the server again and trying calling the query() or getFields() function. There will be an error thrown  
        but this error will not be propagated to the callback function of these functions.

**Comment by clhenrick** [comment]
Relates to #80

**Comment by nermaljcat** [comment]
Look at: https://github.com/omnisci/mapd-connector/blob/master/thrift/browser/thrift.js#L336-L346
